# Generated by Django 3.2.19 on 2023-06-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0002_auto_20230625_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydatki',
            name='miesiac',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.lista_miesiecy'),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='rok',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.lista_lat'),
        ),
    ]
