# Generated by Django 3.2.19 on 2023-06-25 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0004_auto_20230625_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cele',
            name='kwota',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Wartość musi być większa niż 0.')]),
        ),
        migrations.AlterField(
            model_name='cele',
            name='nazwa',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Nazwa powinna składać się przynajmniej z 2 znaków.'), django.core.validators.MaxLengthValidator(50, 'Nazwa może zawierać maksymalnie 50 znaków.')]),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='nazwa',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Nazwa kategorii powinna składać się przynajmniej z 2 znaków.'), django.core.validators.MaxLengthValidator(30, 'Nazwa kategorii może zawierać maksymalnie 50 znaków.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=250, validators=[django.core.validators.EmailValidator('Podaj poprawny adres email.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='imie',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Imię powinno składać się przynajmniej z 2 znaków.'), django.core.validators.MaxLengthValidator(30, 'Imię może zawierać maksymalnie 30 znaków.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='nazwisko',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Nazwisko powinno składać się przynajmniej z 2 znaków.'), django.core.validators.MaxLengthValidator(30, 'Nazwisko może zawierać maksymalnie 30 znaków.')]),
        ),
        migrations.AlterField(
            model_name='przychody',
            name='nazwa_przychodu',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Nazwa powinna składać się przynajmniej z 2 znaków.'), django.core.validators.MaxLengthValidator(50, 'Nazwa może zawierać maksymalnie 50 znaków.')]),
        ),
        migrations.AlterField(
            model_name='przychody',
            name='przychod',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Wartość musi być większa niż 0.')]),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='kategoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.kategoria'),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='kwota',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Wartość musi być większa niż 0.')]),
        ),
    ]
