# Generated by Django 3.2.19 on 2023-06-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('kwota', models.FloatField(unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cele miesięczne',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Osoby',
            },
        ),
        migrations.CreateModel(
            name='Przychod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_przychodu', models.CharField(max_length=100)),
                ('przychod', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Przychod',
            },
        ),
        migrations.CreateModel(
            name='Przychody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_przychodu', models.CharField(max_length=100)),
                ('przychod', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Przychody',
            },
        ),
        migrations.CreateModel(
            name='Wydatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.FloatField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.kategoria')),
            ],
            options={
                'verbose_name_plural': 'Wydatki',
            },
        ),
    ]
