# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wydatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.FloatField(unique=True)),
                ('kategoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Osoby'},
        ),
    ]
