# Generated by Django 3.2.19 on 2023-06-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0002_auto_20230625_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydatki',
            name='miesiac',
            field=models.ForeignKey(default='styczeń', on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.lista_miesiecy1'),
        ),
        migrations.AddField(
            model_name='wydatki',
            name='rok',
            field=models.ForeignKey(default='2023', on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.lista_lat1'),
        ),
    ]
