# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0002_auto_20230603_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
            },
        ),
    ]
