# Generated by Django 3.2.19 on 2023-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0003_auto_20230625_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cele',
            name='kwota',
            field=models.FloatField(),
        ),
    ]
