# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0004_auto_20230603_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydatki',
            options={'verbose_name_plural': 'Wydatkies'},
        ),
    ]
