# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0005_auto_20230603_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wydatki',
            options={'verbose_name_plural': 'Wydatki'},
        ),
        migrations.AddField(
            model_name='wydatki',
            name='Osoba',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.Person'),
        ),
        migrations.AlterField(
            model_name='wydatki',
            name='kategoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.Kategoria'),
        ),
    ]
