# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0006_auto_20230603_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przychody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Przychody',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
