# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0007_auto_20230603_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Przychody',
        ),
    ]
