# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0008_delete_przychody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Przychody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa1', models.CharField(max_length=100, unique=True)),
                ('kwota1', models.IntegerField(unique=True)),
                ('osoba1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.Person')),
            ],
            options={
                'verbose_name_plural': 'Przychody',
            },
        ),
    ]
