# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0009_przychody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przychody',
            name='kwota1',
        ),
        migrations.RemoveField(
            model_name='przychody',
            name='nazwa1',
        ),
        migrations.RemoveField(
            model_name='przychody',
            name='osoba1',
        ),
        migrations.AddField(
            model_name='przychody',
            name='kwota',
            field=models.FloatField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='przychody',
            name='nazwa',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='przychody',
            name='osoba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.Person', unique=True),
        ),
    ]
