# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0010_auto_20230603_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='przychody',
            old_name='nazwa',
            new_name='nazwa_przychodu',
        ),
        migrations.RenameField(
            model_name='przychody',
            old_name='kwota',
            new_name='przychod',
        ),
    ]
