# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0011_auto_20230603_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='przychody',
            name='data',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='przychody',
            name='nazwa_przychodu',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='przychody',
            name='osoba',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.Person'),
        ),
        migrations.AlterField(
            model_name='przychody',
            name='przychod',
            field=models.FloatField(unique=True),
        ),
    ]
