# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0012_auto_20230603_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cele_miesieczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_celu', models.CharField(max_length=200, unique=True)),
                ('kwota', models.FloatField(unique=True)),
                ('opis', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
