# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0013_cele_miesieczne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cele_miesieczne',
            old_name='nazwa_celu',
            new_name='nazwa',
        ),
        migrations.AlterField(
            model_name='cele_miesieczne',
            name='opis',
            field=models.TextField(blank=True),
        ),
    ]
