# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-03 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0014_auto_20230603_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cele_miesieczne',
            new_name='Cele',
        ),
        migrations.AlterModelOptions(
            name='cele',
            options={'verbose_name_plural': 'Cele miesięczne'},
        ),
    ]
