# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2023-06-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budzet_domowy', '0015_auto_20230603_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydatki',
            name='Osoba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budzet_domowy.Person', unique=True),
        ),
    ]
